# Generated by Django 4.2.3 on 2023-08-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='trial',
        ),
    ]
