# Generated by Django 4.2.3 on 2023-08-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_subscription_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=15, unique=True, verbose_name='Phone Number'),
        ),
    ]
